# Path to your oh-my-bash installation.
export OSH=/home/${USER}/.oh-my-bash

# if command -v tmux &> /dev/null \
# 	&& [ -n "$PS1" ] \
# 	&& [[ ! "$TERM" =~ screen ]] \
# 	&& [[ ! "$TERM" =~ tmux ]] \
# 	&& [ -z "$TMUX" ]; then
#   exec tmux
# fi

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-bash is loaded.
#OSH_THEME="font"
#OSH_THEME="90210"
#OSH_THEME="brainy"
OSH_THEME="lambda"
#OSH_THEME="luan"
#OSH_THEME="nekolight"
#OSH_THEME="lucky"
#
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_OSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $OSH/custom?
# OSH_CUSTOM=/path/to/new-custom-folder

# Which completions would you like to load? (completions can be found in ~/.oh-my-bash/completions/*)
# Custom completions may be added to ~/.oh-my-bash/custom/completions/
# Example format: completions=(ssh git bundler gem pip pip3)
# Add wisely, as too many completions slow down shell startup.
completions=(
  git
  composer
  ssh
)

# Which aliases would you like to load? (aliases can be found in ~/.oh-my-bash/aliases/*)
# Custom aliases may be added to ~/.oh-my-bash/custom/aliases/
# Example format: aliases=(vagrant composer git-avh)
# Add wisely, as too many aliases slow down shell startup.
aliases=(
 # general
)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  bashmarks
)

source $OSH/oh-my-bash.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-bash libs,
# plugins, and themes. Aliases can be placed here, though oh-my-bash
# users are encouraged to define aliases within the OSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias bashconfig="mate ~/.bashrc"
# alias ohmybash="mate ~/.oh-my-bash"
alias githubdmn="git config user.email \"dmninbox@gmail.com\" && git config user.name \"githubdmn\""
alias gitlabdmn="git config user.email \"dmninbox@gmail.com\" && git config user.name \"gitlabdmn\""
alias upgrade="~/dotfiles/upgrade.sh"
alias update_apps="~/dotfiles/update_apps.sh"
alias tor="~/Downloads/tor-browser/Browser/start-tor-browser"
alias iris="~/dotfiles/iris/iris-micro.sh"

nvimbash() {
  touch "$1" && chmod +x "$1" && nvim "$1"
}

nanobash() {
  touch "$1" && chmod +x "$1" && nano "$1"
}

# Compile: Specifically targets the Maven-style src/main/java root
jcompile() {
    # 1. Clean and setup the bin directory
    mkdir -p bin
    
    # 2. Find all .java files under the package root
    # We use -sourcepath to tell javac where the 'com' package actually starts
    find src/main/java -name "*.java" > .sources.txt
    
    if [ -s .sources.txt ]; then
        javac -d bin -sourcepath src/main/java @.sources.txt
        echo "Successfully compiled to ./bin"
    else
        echo "Error: No .java files found in src/main/java"
    fi
    rm .sources.txt
}

# Run: Automatically identifies the main class based on the 'bin' structure
jrun() {
    if [ ! -d "bin" ]; then
        echo "Error: No 'bin' directory found. Run jcompile first."
        return 1
    fi

    # This logic finds the App.class and strips 'bin/' to get the true package name
    # e.g., bin/com/example/app/App.class -> com.example.app.App
    local main_class=$(find bin -name "App.class" | sed 's|bin/||' | sed 's|\.class||' | tr '/' '.')

    if [ -z "$main_class" ]; then
        echo "Error: Could not find App.class in bin/"
        return 1
    fi

    echo "Running: $main_class"
    java -cp bin "$main_class"
}


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$HOME/sqlite
#export PATH="${PATH}:${HOME}/go/bin/"
# let Go use its own GOROOT
unset GOROOT

# keep your module cache / installs under ~/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin


# export PATH="${PATH}:${HOME}/gradle/bin/"
# export JAVA_HOME=${HOME}/jdk-21
# export PATH=$PATH:$JAVA_HOME/bin
# export PATH=$PATH:$HOME/gradle/gradle-8.10.2/bin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

alias javaCompile="find src -name "*.java" | xargs javac -d bin"
alias javaClean="rm -rf bin"

# export DENO_INSTALL="$HOME/.deno"
# export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="$HOME/bin:$PATH"export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# OLD Xorg
# alias xcopy='xclip -selection clipboard'
# alias xpaste='xclip -selection clipboard -o'
# Wayland-Safe Alternative
# alias xcopy='wl-copy'
# alias xpaste='wl-paste'





