# version: '3.8'

services:
  debian-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev
    tty: true      # Allocates a terminal for interactive use
    stdin_open: true # Keeps the container open for interaction
    volumes:
      - ./devuser:/home/devuser  # Bind mount a local directory to the container's /workspace
    environment:
      - DEBIAN_CLI=noninteractive  # Prevents interactive prompts during installation
    networks:
      - debian_network
    ports:
      - "5173:3000"  # Map host port 5173 to container port 3000 (assuming your Node.js app listens on port 3000) 

networks:
  debian_network:
    driver: bridge
